# Generated by Django 3.0.2 on 2020-01-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(null=True)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
