# Generated by Django 3.0.2 on 2020-01-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentropy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='sensitive',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
