# Generated by Django 3.0.2 on 2020-01-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentropy', '0003_hacker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
