# Generated by Django 3.0.2 on 2020-01-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentropy', '0004_auto_20200121_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
