# Generated by Django 3.0.2 on 2020-01-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentropy', '0005_auto_20200121_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
